esphome:
  name: oled
esp32:
  board: esp32-s3-devkitc-1
external_components:
  - source:
      type: local
      path: components      
wifi:
  ssid: Wokwi-GUEST
web_server:
logger:
oled:
  - sda: 5
    scl: 4
    id: oled_1
    index: 1
  - sda: 7
    scl: 6
    id: oled_2
   index: 2


